import copy
import hashlib
import importlib.util
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


SCRIPT = Path(__file__).resolve().parents[1] / "scripts" / "source_md.py"
SPEC = importlib.util.spec_from_file_location("source_md", SCRIPT)
SOURCE_MD = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(SOURCE_MD)


def dump(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def chunk_text(task, body_text, chapter_heading="Synthetic Chapter"):
    pages = ",".join(page.split(":", 1)[1] for page in task["processing_pages"])
    return (
        "---\n"
        f'id: "{task["id"]}"\n'
        f'pdf_pages: "{pages}"\n'
        f'pages: "{pages}"\n'
        f'chapter: "{task["chapter"]}"\n'
        f'section: "{task["section"]}"\n'
        f'title: "{task["title"]}"\n'
        f'batch_id: "{task["batch_id"]}"\n'
        "---\n"
        f"# {chapter_heading}\n"
        f'## {task["title"]}\n'
        f"{body_text}"
    )


def make_task(task_id, batch_id, section, title, pages, output, regions):
    return {
        "id": task_id,
        "batch_id": batch_id,
        "chapter": "C1",
        "section": section,
        "title": title,
        "expected_pages": pages,
        "processing_pages": pages,
        "output": output,
        "status": "pass",
        "locators": [
            {
                "page": page,
                "printed_page": page.split(":", 1)[1],
                "source_region": region,
                "destination_heading": f"## {title}",
            }
            for page, region in zip(pages, regions)
        ],
    }


class BatchFixture:
    def __init__(self, root):
        self.root = root
        self.pages = {}
        for number in range(1, 4):
            path = root / "pages" / "S" / f"page-{number:03}.jpg"
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(f"original synthetic image {number}\n".encode())
            self.pages[f"S:{number:03}"] = path

        dump(
            root / "sources.json",
            [
                {
                    "id": "S",
                    "kind": "images",
                    "original": "Synthetic bytes generated by the test",
                    "sha256": None,
                    "dpi": None,
                    "edition": "Synthetic edition",
                    "pages": [
                        {
                            "id": page_id,
                            "pdf_page": number,
                            "printed_page": f"{number:03}",
                            "image": f"pages/S/page-{number:03}.jpg",
                            "sha256": digest(self.pages[page_id]),
                            "width": 1,
                            "height": 1,
                            "disposition": "include",
                            "reason": "",
                        }
                        for number, page_id in enumerate(self.pages, 1)
                    ],
                }
            ],
        )
        dump(root / "source-map.json", {"source_id": "S", "fixture": "synthetic"})
        dump(root / "inventory-review.json", {"status": "pass", "unresolved_count": 0})
        self.batches = [
            {
                "id": "B1",
                "expected_pages": ["S:001", "S:002"],
                "processing_pages": ["S:001", "S:002"],
                "fragment": "fragments/B1.json",
                "chapter_keys": ["C1"],
                "inventory_status": "pass",
            },
            {
                "id": "B2",
                "expected_pages": ["S:003"],
                "processing_pages": ["S:003"],
                "fragment": "fragments/B2.json",
                "chapter_keys": ["C1"],
                "inventory_status": "pass",
            },
        ]
        dump(root / "batches.json", self.batches)

        first = make_task(
            "B1-S1",
            "B1",
            "C1.1",
            "First Section",
            ["S:001"],
            "chunks/B1/first.md",
            ["upper region"],
        )
        second = make_task(
            "B1-S2",
            "B1",
            "C1.2",
            "Second Section",
            ["S:001", "S:002"],
            "chunks/B1/second.md",
            ["lower region", "whole page"],
        )
        continuation = make_task(
            "B2-S2",
            "B2",
            "C1.2",
            "Second Section",
            ["S:003"],
            "chunks/B2/continuation.md",
            ["continuation region"],
        )
        self.write_batch("B1", [first, second], ["alpha  \n\n", "beta\tvalue\n"])
        self.write_batch(
            "B2",
            [continuation],
            ["gamma\n## Second Section\ninternal repeated heading remains\n"],
        )
        self.refresh_canonical()

    def write_batch(self, batch_id, tasks, bodies):
        batch = next(batch for batch in self.batches if batch["id"] == batch_id)
        for task, body in zip(tasks, bodies):
            path = self.root / task["output"]
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(chunk_text(task, body), encoding="utf-8", newline="")
            task["chunk_sha256"] = digest(path)
        fragment = {
            "batch_id": batch_id,
            "source_id": "S",
            "status": "pass",
            "tasks": tasks,
            "review": f"reviews/{batch_id}.json",
        }
        dump(self.root / batch["fragment"], fragment)
        page_regions = {
            page: [
                locator["source_region"]
                for task in tasks
                for locator in task["locators"]
                if locator["page"] == page
            ]
            for page in batch["processing_pages"]
        }
        review = {
            "batch_id": batch_id,
            "source_id": "S",
            "status": "pass",
            "source_images": [
                {"page": page, "sha256": digest(self.pages[page])}
                for page in batch["processing_pages"]
            ],
            "section_outputs": [
                {"task": task["id"], "chunk_sha256": task["chunk_sha256"]}
                for task in tasks
            ],
            "coverage": [
                {"page": page, "regions": page_regions[page], "status": "pass"}
                for page in batch["processing_pages"]
            ],
            "findings": [],
            "corrections": [],
            "checks": {
                "numerical": "not_applicable",
                "diagram": "not_applicable",
                "false_proposition": "not_applicable",
            },
            "unresolved_count": 0,
            "reviewer_model": "synthetic-test-reviewer",
            "dependency_commits": ["1" * 40],
        }
        dump(self.root / fragment["review"], review)

    def fragment(self, batch_id):
        batch = next(batch for batch in self.batches if batch["id"] == batch_id)
        return json.loads((self.root / batch["fragment"]).read_text(encoding="utf-8"))

    def save_fragment(self, batch_id, fragment):
        batch = next(batch for batch in self.batches if batch["id"] == batch_id)
        dump(self.root / batch["fragment"], fragment)

    def replace_task(self, batch_id, index, *, section=None, title=None, body="replacement\n"):
        fragment = self.fragment(batch_id)
        task = fragment["tasks"][index]
        if section is not None:
            task["section"] = section
        if title is not None:
            task["title"] = title
        for locator in task["locators"]:
            locator["destination_heading"] = f'## {task["title"]}'
        path = self.root / task["output"]
        path.write_text(chunk_text(task, body), encoding="utf-8", newline="")
        task["chunk_sha256"] = digest(path)
        self.save_fragment(batch_id, fragment)
        review_path = self.root / fragment["review"]
        review = json.loads(review_path.read_text(encoding="utf-8"))
        review["section_outputs"] = [
            {"task": item["id"], "chunk_sha256": item["chunk_sha256"]}
            for item in fragment["tasks"]
        ]
        dump(review_path, review)
        self.refresh_canonical()

    def refresh_canonical(self):
        tasks = []
        for batch in self.batches:
            tasks.extend(self.fragment(batch["id"])["tasks"])
        dump(self.root / "tasks.json", tasks)
        dump(
            self.root / "qa" / "chapters" / "C1.json",
            {
                "chapter": "C1",
                "status": "pass",
                "unresolved_count": 0,
                "chunks": [
                    {"task": task["id"], "chunk_sha256": task["chunk_sha256"]}
                    for task in tasks
                ],
            },
        )


class TestLegacyCompatibility(unittest.TestCase):
    def test_legacy_check_and_assemble_remain_available(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            page_paths = []
            for number in (1, 2):
                path = root / "pages" / "L" / f"page-{number:03}.jpg"
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(f"legacy synthetic {number}\n".encode())
                page_paths.append(path)
            dump(
                root / "sources.json",
                [
                    {
                        "id": "L",
                        "kind": "images",
                        "original": "Synthetic legacy fixture",
                        "sha256": None,
                        "dpi": None,
                        "edition": "Legacy synthetic edition",
                        "pages": [
                            {
                                "id": f"L:{number:03}",
                                "pdf_page": number,
                                "printed_page": str(number),
                                "image": f"pages/L/page-{number:03}.jpg",
                                "sha256": digest(page_paths[number - 1]),
                                "width": 1,
                                "height": 1,
                                "disposition": "include",
                                "reason": "",
                            }
                            for number in (1, 2)
                        ],
                    }
                ],
            )
            tasks = []
            for number, title in ((1, "One"), (2, "Two")):
                output = f"chunks/L{number}.md"
                path = root / output
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(
                    "---\n"
                    f"id: L{number}\n"
                    'chapter: "01"\n'
                    "---\n"
                    "# Legacy Chapter\n"
                    f"## {title}\n"
                    f"legacy {number}\n",
                    encoding="utf-8",
                )
                tasks.append(
                    {
                        "id": f"L{number}",
                        "chapter": "01",
                        "section": f"01.{number}",
                        "expected_pages": ["L:001", "L:002"],
                        "processing_pages": [f"L:{number:03}"],
                        "output": output,
                        "status": "pass",
                    }
                )
            dump(root / "tasks.json", tasks)
            SOURCE_MD.source_check(root)
            SOURCE_MD.assemble(root)
            merged = (root / "merged" / "textbook.md").read_text(encoding="utf-8")
            self.assertEqual(merged.count("# Legacy Chapter"), 1)
            self.assertIn("## One", merged)
            self.assertIn("## Two", merged)


class TestBatchMode(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.root = Path(self.temporary.name)
        self.fixture = BatchFixture(self.root)

    def tearDown(self):
        self.temporary.cleanup()

    def assert_rejected(self, callable_, pattern):
        with self.assertRaisesRegex(ValueError, pattern):
            callable_()

    def test_manifest_batch_and_complete_check_accept_valid_fixture(self):
        SOURCE_MD.batch_manifest_check(self.root)
        SOURCE_MD.batch_check(self.root, "B1")
        SOURCE_MD.batch_check(self.root, "B2")
        SOURCE_MD.source_check(self.root)

    def test_check_batch_allows_unfinished_siblings(self):
        second = self.fixture.batches[1]
        (self.root / second["fragment"]).unlink()
        (self.root / "reviews" / "B2.json").unlink()
        (self.root / "chunks" / "B2" / "continuation.md").unlink()
        (self.root / "tasks.json").unlink()
        (self.root / "qa" / "chapters" / "C1.json").unlink()
        SOURCE_MD.batch_check(self.root, "B1")
        self.assert_rejected(lambda: SOURCE_MD.source_check(self.root), "missing fragment")

    def test_multiple_sections_may_cite_regions_of_one_batch_page(self):
        records = SOURCE_MD.batch_check(self.root, "B1")
        self.assertEqual([record["task"]["id"] for record in records], ["B1-S1", "B1-S2"])
        self.assertIn("S:001", records[0]["task"]["processing_pages"])
        self.assertIn("S:001", records[1]["task"]["processing_pages"])

    def test_duplicate_manifest_page_is_rejected(self):
        sources = json.loads((self.root / "sources.json").read_text(encoding="utf-8"))
        sources[0]["pages"].append(copy.deepcopy(sources[0]["pages"][0]))
        dump(self.root / "sources.json", sources)
        self.assert_rejected(lambda: SOURCE_MD.batch_manifest_check(self.root), "Duplicate")

    def test_duplicate_physical_page_number_is_rejected(self):
        sources = json.loads((self.root / "sources.json").read_text(encoding="utf-8"))
        sources[0]["pages"][1]["pdf_page"] = 1
        dump(self.root / "sources.json", sources)
        self.assert_rejected(lambda: SOURCE_MD.batch_manifest_check(self.root), "physical page number")

    def test_missing_batch_owner_is_rejected(self):
        dump(self.root / "batches.json", self.fixture.batches[:1])
        self.assert_rejected(lambda: SOURCE_MD.batch_manifest_check(self.root), "exactly one batch owner")

    def test_duplicate_batch_owner_is_rejected(self):
        batches = copy.deepcopy(self.fixture.batches)
        batches[1]["expected_pages"] = ["S:002", "S:003"]
        batches[1]["processing_pages"] = ["S:002", "S:003"]
        dump(self.root / "batches.json", batches)
        self.assert_rejected(
            lambda: SOURCE_MD.batch_manifest_check(self.root),
            "out of physical source order|more than one batch",
        )

    def test_changed_page_hash_is_rejected(self):
        self.fixture.pages["S:001"].write_bytes(b"changed\n")
        self.assert_rejected(lambda: SOURCE_MD.batch_manifest_check(self.root), "Page changed")

    def test_missing_page_image_is_rejected(self):
        self.fixture.pages["S:001"].unlink()
        self.assert_rejected(lambda: SOURCE_MD.batch_manifest_check(self.root), "Missing page image")

    def test_source_image_path_escape_is_rejected(self):
        sources = json.loads((self.root / "sources.json").read_text(encoding="utf-8"))
        sources[0]["pages"][0]["image"] = "../outside.jpg"
        dump(self.root / "sources.json", sources)
        self.assert_rejected(lambda: SOURCE_MD.batch_manifest_check(self.root), "Path escapes project")

    def test_path_escape_is_rejected(self):
        fragment = self.fixture.fragment("B1")
        fragment["tasks"][0]["output"] = "../outside.md"
        self.fixture.save_fragment("B1", fragment)
        self.assert_rejected(lambda: SOURCE_MD.batch_check(self.root, "B1"), "Path escapes project")

    def test_out_of_batch_locator_is_rejected(self):
        fragment = self.fixture.fragment("B1")
        fragment["tasks"][0]["locators"][0]["page"] = "S:003"
        self.fixture.save_fragment("B1", fragment)
        self.assert_rejected(lambda: SOURCE_MD.batch_check(self.root, "B1"), "out-of-batch chunk locator")

    def test_unresolved_marker_is_rejected_even_with_current_hash(self):
        fragment = self.fixture.fragment("B1")
        task = fragment["tasks"][0]
        path = self.root / task["output"]
        path.write_text(path.read_text(encoding="utf-8") + "[UNRESOLVED: synthetic]\n", encoding="utf-8")
        task["chunk_sha256"] = digest(path)
        self.fixture.save_fragment("B1", fragment)
        self.assert_rejected(lambda: SOURCE_MD.batch_check(self.root, "B1"), "unresolved source content")

    def test_changed_chunk_hash_is_rejected(self):
        path = self.root / "chunks" / "B1" / "first.md"
        path.write_text(path.read_text(encoding="utf-8") + "changed\n", encoding="utf-8")
        self.assert_rejected(lambda: SOURCE_MD.batch_check(self.root, "B1"), "chunk hash changed")

    def test_invalid_fragment_status_is_rejected(self):
        fragment = self.fixture.fragment("B1")
        fragment["status"] = "reviewed"
        self.fixture.save_fragment("B1", fragment)
        self.assert_rejected(lambda: SOURCE_MD.batch_check(self.root, "B1"), "status must be pass")

    def test_invalid_task_status_is_rejected(self):
        fragment = self.fixture.fragment("B1")
        fragment["tasks"][0]["status"] = "pending"
        self.fixture.save_fragment("B1", fragment)
        self.assert_rejected(lambda: SOURCE_MD.batch_check(self.root, "B1"), "status must be pass")

    def test_invalid_inventory_status_is_rejected(self):
        batches = copy.deepcopy(self.fixture.batches)
        batches[0]["inventory_status"] = "pending"
        dump(self.root / "batches.json", batches)
        self.assert_rejected(lambda: SOURCE_MD.batch_manifest_check(self.root), "status must be pass")

    def test_invalid_review_status_is_rejected(self):
        path = self.root / "reviews" / "B1.json"
        review = json.loads(path.read_text(encoding="utf-8"))
        review["status"] = "pending"
        dump(path, review)
        self.assert_rejected(lambda: SOURCE_MD.batch_check(self.root, "B1"), "status must be pass")

    def test_unresolved_review_marker_is_rejected(self):
        path = self.root / "reviews" / "B1.json"
        review = json.loads(path.read_text(encoding="utf-8"))
        review["findings"] = ["[UNRESOLVED: synthetic review]"]
        dump(path, review)
        self.assert_rejected(lambda: SOURCE_MD.batch_check(self.root, "B1"), "unresolved marker")

    def test_review_hash_drift_is_rejected(self):
        path = self.root / "reviews" / "B1.json"
        review = json.loads(path.read_text(encoding="utf-8"))
        review["source_images"][0]["sha256"] = "0" * 64
        dump(path, review)
        self.assert_rejected(lambda: SOURCE_MD.batch_check(self.root, "B1"), "source image hash mismatch")

    def test_missing_locator_coverage_is_rejected(self):
        fragment = self.fixture.fragment("B1")
        fragment["tasks"][1]["locators"] = fragment["tasks"][1]["locators"][:1]
        self.fixture.save_fragment("B1", fragment)
        self.assert_rejected(lambda: SOURCE_MD.batch_check(self.root, "B1"), "locator coverage")

    def test_canonical_tasks_must_equal_ordered_fragments(self):
        tasks = json.loads((self.root / "tasks.json").read_text(encoding="utf-8"))
        dump(self.root / "tasks.json", list(reversed(tasks)))
        self.assert_rejected(lambda: SOURCE_MD.source_check(self.root), "Canonical tasks.json differs")

    def test_chapter_gate_must_be_passed_and_current(self):
        gate_path = self.root / "qa" / "chapters" / "C1.json"
        gate = json.loads(gate_path.read_text(encoding="utf-8"))
        gate["chunks"][0]["chunk_sha256"] = "0" * 64
        dump(gate_path, gate)
        self.assert_rejected(lambda: SOURCE_MD.source_check(self.root), "Chapter review hashes")

    def test_invalid_chapter_gate_status_is_rejected(self):
        gate_path = self.root / "qa" / "chapters" / "C1.json"
        gate = json.loads(gate_path.read_text(encoding="utf-8"))
        gate["status"] = "pending"
        dump(gate_path, gate)
        self.assert_rejected(lambda: SOURCE_MD.source_check(self.root), "status must be pass")

    def test_assembly_rejects_missing_chapter_gate(self):
        (self.root / "qa" / "chapters" / "C1.json").unlink()
        self.assert_rejected(lambda: SOURCE_MD.assemble(self.root), "Missing chapter review gate")

    def test_contradictory_repeated_section_heading_is_rejected(self):
        self.fixture.replace_task("B2", 0, title="Contradictory Section")
        self.assert_rejected(lambda: SOURCE_MD.source_check(self.root), "contradictory repeated section heading")

    def test_return_to_earlier_section_id_is_rejected(self):
        self.fixture.replace_task("B2", 0, section="C1.1", title="First Section")
        self.assert_rejected(lambda: SOURCE_MD.source_check(self.root), "out-of-order continuation")

    def test_assembly_golden_bytes_and_second_run_are_identical(self):
        expected = (
            "# Synthetic Chapter\n"
            "## First Section\n"
            "alpha  \n\n"
            "## Second Section\n"
            "beta\tvalue\n"
            "gamma\n"
            "## Second Section\n"
            "internal repeated heading remains\n"
        ).encode()
        SOURCE_MD.assemble(self.root)
        output = self.root / "merged" / "textbook.md"
        first = output.read_bytes()
        first_hash = digest(output)
        SOURCE_MD.assemble(self.root)
        self.assertEqual(first, expected)
        self.assertEqual(output.read_bytes(), expected)
        self.assertEqual(digest(output), first_hash)
        self.assertEqual(first_hash, hashlib.sha256(expected).hexdigest())
        assembly = json.loads((self.root / "merged" / "assembly.json").read_text(encoding="utf-8"))
        self.assertEqual(assembly["sha256"], first_hash)
        self.assertEqual(
            assembly["chunks"][2]["removed_boundary_headings"],
            ["# Synthetic Chapter", "## Second Section"],
        )

    def test_assembly_preserves_crlf_in_nonremoved_body_bytes(self):
        fragment = self.fixture.fragment("B2")
        task = fragment["tasks"][0]
        raw = chunk_text(task, "")
        prefix = raw[: raw.index("# Synthetic Chapter")]
        raw = prefix + "# Synthetic Chapter\r\n## Second Section\r\ngamma-crlf\r\n"
        path = self.root / task["output"]
        path.write_text(raw, encoding="utf-8", newline="")
        task["chunk_sha256"] = digest(path)
        self.fixture.save_fragment("B2", fragment)
        review_path = self.root / fragment["review"]
        review = json.loads(review_path.read_text(encoding="utf-8"))
        review["section_outputs"] = [
            {"task": task["id"], "chunk_sha256": task["chunk_sha256"]}
        ]
        dump(review_path, review)
        self.fixture.refresh_canonical()
        SOURCE_MD.assemble(self.root)
        self.assertTrue((self.root / "merged" / "textbook.md").read_bytes().endswith(b"gamma-crlf\r\n"))

    def test_cli_help_and_batch_message_document_limits(self):
        help_result = subprocess.run(
            [sys.executable, str(SCRIPT), "--help"], capture_output=True, text=True, check=True
        )
        for command in ("check-manifest", "check-batch", "check", "assemble"):
            self.assertIn(command, help_result.stdout)
        result = subprocess.run(
            [sys.executable, str(SCRIPT), "check-batch", str(self.root), "--batch", "B1"],
            capture_output=True,
            text=True,
            check=True,
        )
        self.assertIn("not proven automatically", result.stdout)


if __name__ == "__main__":
    unittest.main()
